data_source berlin_estate:
  type: postgres
  connection:
    host: localhost
    port: 5432
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DB}
  schema: public
